declare @addedByUsername nvarchar(100) = 'craig.fleming@judi.ai'

insert into Levels (Name) values ('Engineer I')
declare @engineerOneLevelId int = (select Id from Levels where Name = 'Engineer I')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Broad knowledge of CS concepts.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Focus on growing as an engineer, learning existing tools, resources and processes.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Developers their productivity skills by learning source control, edits, the build system, and other tools as well as testing best practices.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Capable of taking well-defined sub-tasks and completing these tasks.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Developing knowledge of a single component of our architecture.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Effective in communicating status to the team.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Exhibits core values, focuses on underanding and living these values.', @addedByUsername, GETDATE(), @engineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Accepts feedback graciously and learns from everything they do.', @addedByUsername, GETDATE(), @engineerOneLevelId)


insert into Levels (Name) values ('Engineer II')
declare @engineerTwoLevelId int = (select Id from Levels where Name = 'Engineer II')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Writes correct and clean code with guidance, consistently follows stated best practices.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Participantes in technical design of features with guidance.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Rarely makes the same mistake twice.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Begins to focus on attaining expertise in one or more areas (eg, JS/C# dev, performance, UX)', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Learns quickly and makes steady progres without the need for constant significant feedback from more senior engineers.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Makes steady progress on tasks; knows when to ask for help in order to get themselves unblocked.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Able to own small-to-medium features from technical design through completion.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Capable of prioritizing tasks; avoids getting caught up in unimportant details and endless "bikeshedding".', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Self-sufficient in at least one large area of the codebase, with a high-level understanding of other components.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Capable of providing support for their area, including systems that they are not familiar with.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Gives timely, helpful feedback to peers and managers.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Communicates assumptions and gets clarification on tasks up front to minimize the need for rework.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Solicits feedback from others and is earer to find ways to improve.', @addedByUsername, GETDATE(), @engineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Understands how their work fits in to the larger project and identifies problems with requirements.', @addedByUsername, GETDATE(), @engineerTwoLevelId)


insert into Levels (Name) values ('Senior Engineer I')
declare @seniorEngineerOneLevelId int = (select Id from Levels where Name = 'Senior Engineer I')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Understands and makes well-reasoned design decisions and tradeoffs in their area; able to work in other areas of the codebase with guidance.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Doesn''t flail while debugging.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Demonstrates knowledge of industry trends, our infrastructure and out build system.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Persistent in the face of roadblocks, dispatches them efficiently, pulling in others as necessary. Requires minimal direction or oversight.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Takes the initiative to fix issues before being assigned them.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Seeks empirical evidence through proof of concepts, tests and external research.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Delivers complex products to QA that they believe are well-baked and bug-free.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('End-to-end responsibility on projects of increasing complexity, contributes to common code.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Looks at test cases and advises QA on adjacent code/regression impact.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Understands the business supported by the code they support.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Partners with Product and drives requirements that take into account all parties needs.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Possesses empathy with the user of the software they are producing and uses that empathy to guide decision-making.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Identifies problems/risks of own work and others.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Communicates effectively cross functions; is able to work well with Product, Design, Data Science, etc as necessary.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Proactively identifies problems with requirements for their own work and adjacent work, and communicates these issues early to help course-correct.', @addedByUsername, GETDATE(), @seniorEngineerOneLevelId)


insert into Levels (Name) values ('Senior Engineer II')
declare @seniorEngineerTwoLevelId int = (select Id from Levels where Name = 'Senior Engineer II')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Go-to export in one area of the codebase, understands the broad architecture of the entire system.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Provides echnical advice and weights in on technical decisions that impact other teams or the company at large.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Researches and proposes new technologies.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Scopes and stages work into well-defined milestones to avoid a monolithic deliverable.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Regularly delivers software on-time and is constantly working to make accurate estimates and deliver on those estimates.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Known for drama-free launches.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Owns the technical testing and performance plan for their projects.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Takes initiative to identify and solve important problems, coordinating with others on cross-cutting technical issues.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Sets direction at the project/service level and consistently influences decision-making.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Identifies and proactively tackles technical debt before it grows into debt that requires signficicant up-front work to resolve.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Makes others better through code reviews, thorough documentation, technical guideance, and mentoring or serving as a Tech Lead on a project.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Collaborates on architecture review and provides feedback on projects outside of their core area.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Understands the tradeoffs between technical and product needs and leads to solutions that take all of these needs into account.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Identifies and proposes strategies around technical problems affecting their team, communicates standards and gets buy-in on solutions.', @addedByUsername, GETDATE(), @seniorEngineerTwoLevelId)


insert into Levels (Name) values ('Staff Engineer')
declare @staffEngineerLevelId int = (select Id from Levels where Name = 'Staff Engineer')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Sought out for technical guidance.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Anticipates technical issues at the product level and makes architectural and design decisions to avoid them.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Owner of and expert on large sections of our codebase.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('A record of creating sweeping improvements in stability, performance, and scalability across major business-critical systems.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Recgognized as a prolific contributor to core and side projects.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Consistently able to reduce the complexity of projects, services and processes in order to get more done with less work.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Shapes broad architecture; ships multiple large services, complex libraries or major pieces of infrastructure.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Has made an obvious postive impact on the entire company''s technical trajectory.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Multiplies the ffectiveness of others by facilitating cross-team work.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Listens and guides debates to help reach a consensus; once a decision is made, clearly communicates and backs that decision.', @addedByUsername, GETDATE(), @staffEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Sets short to medium-term strategic technical direction; able to look ahead 6-12 months and identity the areas of greatest need and create plans to improve them.', @addedByUsername, GETDATE(), @staffEngineerLevelId)


insert into Levels (Name) values ('Senior Staff Engineer')
declare @seniorStaffengineerLevelId int = (select Id from Levels where Name = 'Senior Staff Engineer')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Anticipates broad technical change and ensures we are always ahead of the curve', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Able to recognize and make trade-offs with respect to the whole system.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Understands deeply the entire architecure for a major part of our business and is able to articulate clearly the scaling and reliability limits of that area.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Consistently delivers large systems involving one or more teams'' contribution on time at a high level of quality.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Quickly breaks down complex problems into potention solutions, knowns, and unknowns, in order to get to solid resolutions faster.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Capable of debugging the hairiest problems that the team encounters.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Plays a key role in developing multi-year technology strategy for complete and critical areas of the business that encompass multiple systems and teams.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Decisions have a direct impact on our long-term success or failure.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Creates architecture that enables many potential futures without knowing exactly what the future is.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Primarily acts as a multiplier by building systems, authoring tools, or introducing policies or patterns that raise the level of productivity of the entire org.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Communicates the awesomeness of out tech community externally via talks and blog posts. Identifies areas that we can share effectively with the outside world and guides the creation of content and communication around these areas', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Leads the conversations internally about the direction of major areas of the technology, drives wide-team consensus to the adoption of this direction, and uses this direction to inspire engineers.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Seen as a role model and mentor to every technical member of the team.', @addedByUsername, GETDATE(), @seniorStaffengineerLevelId)


insert into Levels (Name) values ('Principle Engineer/Chief Architect')
declare @principleEngineerLevelId int = (select Id from Levels where Name = 'Principle Engineer/Chief Architect')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Setting Technical Direction.', @addedByUsername, GETDATE(), @principleEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Puts the "stuff" in "Getting Stuff Done".', @addedByUsername, GETDATE(), @principleEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Identifies technology strategic growth opportunities that enable us to grow as a business.', @addedByUsername, GETDATE(), @principleEngineerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Communicates multi-year technical strategy and leads the team in identifying futher strategic areas for development.', @addedByUsername, GETDATE(), @principleEngineerLevelId)


insert into Levels (Name) values ('Tech Lead')
declare @techLeadLevelId int = (select Id from Levels where Name = 'Tech Lead')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Scales themselves by delegating effectively; ensures tasks are completed as specified without micromanaging.', @addedByUsername, GETDATE(), @techLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Focused on and responsible for the team''s productivity and collective impact.', @addedByUsername, GETDATE(), @techLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Makes independent decisions for the team; is actively learning how to handle difficult management situations.', @addedByUsername, GETDATE(), @techLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Contributes to the career development of others.', @addedByUsername, GETDATE(), @techLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('When the tech lead is acting as the reporting manager to others, the tech lead is expected to meet regularly with their direct reports, provide frequent feedback on their work, help the individuals set goals and work with the engineering lead or director to ensure employee growth and retention goals.', @addedByUsername, GETDATE(), @techLeadLevelId)


insert into Levels (Name) values ('Engineering Lead')
declare @engineeringLeadLevelId int = (select Id from Levels where Name = 'Engineering Lead')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Understands and practices agile software development and management.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Produces quality metrics on the SDLC process.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Ensures team software is monitorable and HA.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Proactive in identifying and clearing roadblocks for the team.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Continues to contribute bug fixes and small features without becoming a bottleneck for the team.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Excels at getting the team to focus on the highest-impact projects.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Able to lead recruiting efforts and determine headcount for their team.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Partners effectively with product to manage scope and delierables for the technical side of the product roadmap.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Manages independently; communicates context to the team and surfaces requirements to upper management.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Sets clear expectations for team members; solicits, synthesizes and delivers feedback.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Communicates timeline, scope and technical concerns to partners.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Leads delivery of major initiatives on clear timelines.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Able to identify areas of strategic technical debt and provide cost/benefit analysis for eliminating this debt and suggested timelines for how to prioritize it.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Comfortable managing team members with different skill sets and technical areas of focus.', @addedByUsername, GETDATE(), @engineeringLeadLevelId)


insert into Levels (Name) values ('Engineering Director')
declare @engineeringDirectorLevelId int = (select Id from Levels where Name = 'Engineering Director')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Ensures their organization has appropriately high technical competence and strives for excellence.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Researches new technologies to stay abreast of industry trends and standards.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Capable of jumping in to help debug and triage critical systems as needed. ', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Contributes to architecture by asking the right questions to ensure architecture matches business needs for the area.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Develops and deploys new strategies for building a high velocity, high performance development organization in line with our emerging customer needs.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Supports technical innovation and leads the creation, continual refinement, and active enforcement of our development standards in order to ensure that our technology can be leveraged as a sustainable competitive advantage.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Participates in staff recruitment, performance assessments, training, and career development. Responsible for all headcount planning and personnel evolution for multiple areas of the engineering organization.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('As necessary, the director manages vendor and external relationships for their organization, and participates in the budgeting process.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Provides leadership to software development managers, addresses technical, resource and personnel issues.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Proactively nurtures the talent of the senior staff in their areas.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Builds and supports high functioning, motivated teams. ', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Creates an organization that understands how to balance technical debt vs business goals.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Collaborates across functional areas to define, prioritize and ensure implementation of specific innovations to improve technical functionality in support of business needs, efficiencies and revenue.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Able to communicate technical concepts to business stakeholders as well as communicate business objectives to the technical team.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Leverages past experience and uses strong communication skills to collaborate effectively with all stakeholders including customers, senior management and other business leaders.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Sells us as a company and their organization as a team to potential candidates. Inspires potential recruits to join the company.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Owns the OKR setting and review process for teams under their oversight.', @addedByUsername, GETDATE(), @engineeringDirectorLevelId)


insert into Levels (Name) values ('VP of Engineering')
declare @vpEngineeringLevelId int = (select Id from Levels where Name = 'VP of Engineering')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Contributes to architectural decisions with a focus on the product and business needs now and in the future, knows the right questions to ask to help the team get to the right decision.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Greatest technical strength is debugging organizations and processes.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Figures out what the "stuff" is across the organization from the tech perspective.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('In partnership with the CTO, product leads, and other business stakeholders, translates the high-level strategic vision into a clear and actionable technology roadmap.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Actively identifies bottlenecks across the organization and works to remove them.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Ensures that every member of the team understands the business goals for the quarter and has bought in to these goals.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Identifies areas for process evolution or clarification, gathers the stakeholders and creates and communicates the strategy for resolving these issues.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Clearly articulates the needs from a personnel and cultural standpoint that will move the engineering organization to the next level.', @addedByUsername, GETDATE(), @vpEngineeringLevelId)


insert into Levels (Name) values ('Chief Technology Officer')
declare @chiefTechnologyOfficerLevelId int = (select Id from Levels where Name = 'Chief Technology Officer')
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Setting Company-wide Technical Direction.', @addedByUsername, GETDATE(), @chiefTechnologyOfficerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Setting Engineering Organizational Priority.', @addedByUsername, GETDATE(), @chiefTechnologyOfficerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Ensures the architecture being built can support multiple future possibilities of the business.', @addedByUsername, GETDATE(), @chiefTechnologyOfficerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Puts the "stuff" in "Getting Stuff Done".', @addedByUsername, GETDATE(), @chiefTechnologyOfficerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Capable of identifying business growth opportunities enabled by technology and executing against those opportunities.', @addedByUsername, GETDATE(), @chiefTechnologyOfficerLevelId)
insert into Skills (Summary, AddedByUsername, AddedOn, LevelId) values ('Communicates executive-level strategy and helps break down business directives into technology goals.', @addedByUsername, GETDATE(), @chiefTechnologyOfficerLevelId)

